/**
 * Turns data/questions/*.json into a SQL migration that loads the question bank.
 *
 *   npm run db:questions
 *
 * Writes supabase/migrations/20260925000001_question_bank.sql. The inserts use
 * ON CONFLICT DO NOTHING, so questions edited in the admin panel are never
 * overwritten. Run `npm run validate:questions` first.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { schemaTablesFor } from "../data/schema";
import { DIFFICULTIES, type Question } from "../types/question";

const OUT = path.join(process.cwd(), "supabase", "migrations", "20260925000001_question_bank.sql");
const BATCH = 50;

const lit = (value: string) => `'${value.replace(/'/g, "''")}'`;
const text = (value: string | undefined | null) => (value == null ? "null" : lit(value));
const textArray = (values: string[] | undefined | null, nullable = false) => {
  if (!values) return nullable ? "null" : "'{}'::text[]";
  return values.length ? `array[${values.map(lit).join(", ")}]::text[]` : "'{}'::text[]";
};
const json = (value: unknown) => (value == null ? "null" : `${lit(JSON.stringify(value))}::jsonb`);

function row(q: Question): string {
  return `(${[
    q.id,
    lit(q.difficulty),
    lit(q.type),
    lit(q.topic),
    lit(q.question),
    lit(q.answer),
    textArray(q.alternatives),
    textArray(q.options, true),
    text(q.query),
    json(q.sampleTables),
    textArray(q.tokens, true),
    textArray(q.distractors),
    text(q.hint),
    lit(q.explanation),
    textArray(schemaTablesFor(q)),
  ].join(", ")})`;
}

function main() {
  const questions: Question[] = DIFFICULTIES.flatMap((d) =>
    JSON.parse(readFileSync(path.join(process.cwd(), "data", "questions", `${d}.json`), "utf8")),
  );
  const columns =
    "id, difficulty, type, topic, question, answer, alternatives, options, query, sample_tables, tokens, distractors, hint, explanation, schema_tables";

  const chunks: string[] = [];
  for (let i = 0; i < questions.length; i += BATCH) {
    const rows = questions
      .slice(i, i + BATCH)
      .map(row)
      .join(",\n");
    chunks.push(`insert into public.questions (${columns}) values\n${rows}\non conflict (id) do nothing;`);
  }

  const sql = `-- Generated by scripts/generate-question-bank.ts from data/questions/*.json. Do not edit by hand.
-- ${questions.length} questions: easy 1-100, medium 101-200, hard 201-300, expert 301-400.

${chunks.join("\n\n")}

-- Continue new ids after the seeded ones.
select setval(pg_get_serial_sequence('public.questions', 'id'), greatest((select max(id) from public.questions), 1));
`;
  writeFileSync(OUT, sql);
  console.log(`Wrote ${questions.length} questions to ${path.relative(process.cwd(), OUT)}`);
}

main();
